spring.application.name=${SPRING_APPLICATION_NAME:StudentGrader}

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# Database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Hot reload
spring.devtools.restart.enabled=false

server.port=${PORT:8080}


# Mail configuration
#spring.mail.host=${MAIL_HOST}
#spring.mail.port=${MAIL_PORT}
#spring.mail.username=${MAIL_USERNAME}
#spring.mail.password=${MAIL_PASSWORD}
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true

# MAIL (safe fallback)
spring.mail.host=${MAIL_HOST:}
spring.mail.port=${MAIL_PORT:}
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.mail.MailSenderAutoConfiguration